# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
zero_arr=np.zeros(10)

In [3]:
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
one_arr=np.ones(10)

In [5]:
one_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [8]:
five_arr=np.ones(10)*5

In [9]:
five_arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [20]:
arr=np.arange(10,51,1)

In [21]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [22]:
even_arr=np.arange(10,51,2)

In [23]:
even_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
matrix=np.arange(0,9,1).reshape(3,3)

In [26]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [28]:
ident=np.eye(3,3)

In [29]:
ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [32]:
rand_num=np.random.rand(1)

In [33]:
rand_num

array([0.2525584])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [34]:
rand_nums=np.random.randn(25)

In [35]:
rand_nums

array([ 0.84880529,  0.44944409,  0.20369438,  0.06768757,  1.05034568,
        0.7849861 , -0.74682914, -0.53051156,  1.03742282, -1.14414662,
        2.49775873,  0.60896432, -0.55762846,  1.07376901, -1.52896913,
        0.89043255, -0.19679355, -0.18448643,  1.00016893, -0.96554006,
        0.22745012,  0.52769888, -1.70261678, -0.16275777, -0.22786578])

#### Create the following matrix:

In [36]:
rand_mat=rand_nums.reshape(5,5)

In [37]:
rand_mat

array([[ 0.84880529,  0.44944409,  0.20369438,  0.06768757,  1.05034568],
       [ 0.7849861 , -0.74682914, -0.53051156,  1.03742282, -1.14414662],
       [ 2.49775873,  0.60896432, -0.55762846,  1.07376901, -1.52896913],
       [ 0.89043255, -0.19679355, -0.18448643,  1.00016893, -0.96554006],
       [ 0.22745012,  0.52769888, -1.70261678, -0.16275777, -0.22786578]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [39]:
linear_arr=np.linspace(0,1, 20)

In [40]:
linear_arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [41]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
mat1=mat[2:,1:]

In [43]:
mat1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [44]:
x=mat[3,4]

In [45]:
x

20

In [46]:
vec1=mat[:3,1]

In [47]:
vec1

array([ 2,  7, 12])

In [48]:
vec2=mat[4,:]

In [49]:
vec2

array([21, 22, 23, 24, 25])

In [50]:
mat4=mat[3:,:]

In [52]:
mat4

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [53]:
sum_mat=np.sum(mat)

In [54]:
sum_mat

325

#### Get the standard deviation of the values in mat

In [55]:
std_mat=np.std(mat)

In [56]:
std_mat

7.211102550927978

#### Get the sum of all the columns in mat

In [57]:
col_mat=np.sum(mat,axis=0)

In [58]:
col_mat

array([55, 60, 65, 70, 75])

# Great Job!